name: Test all functions, build marketplace

on:
  push:
    branches:
      - ci

jobs:

  build-marketplace:
    name: Build marketplace
    if: github.repository == 'mlrun/functions' && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    continue-on-error: true
    
    steps:
      - name: Get the current branch name
        shell: bash
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
        id: branch
      - name: Checkout current repo
        uses: actions/checkout@v2
        with:
          path: functions
      - name: Checkout Marketplace
        uses: actions/checkout@v2
        with:
          repository: mlrun/marketplace
          path: marketplace
      - name: Install python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install requirements
        run: |
          cd functions
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build marketplace docs
        env:
          CHANNEL: ${{ steps.branch.outputs.branch }}
        run: |
          cd marketplace
          pwd
          git pull origin
          cd ..
          python functions/functions.py build-marketplace -s functions -m marketplace -c $CHANNEL -v -f
      - name: Publish marketplace release
        env:
          GITHUB_TOKEN: ${{ secrets.MARKETPLACE_ACCESS_TOKEN_V3 }}
          USERNAME: iguazio-cicd
          REPO_PATH: marketplace
          BASE_REPO: mlrun
          BASE_BRANCH: master
        run: |
          cd marketplace
          pwd
          COMMIT_SHA=$(git rev-parse --short "$GITHUB_SHA")
          echo "commit sha: $COMMIT_SHA"
          echo "github sha: $GITHUB_SHA"
          BRANCH_NAME=marketplace-doc-gen-$COMMIT_SHA
          REMOTE=https://$USERNAME:$GITHUB_TOKEN@github.com/$BASE_REPO/$REPO_PATH.git
          echo "Validating environment params...";
          [ -z "${GITHUB_TOKEN}" ] && {
              echo 'Missing input "GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}".';
              exit 1;
          };
          git config --local user.name $USERNAME
          git branch --set-upstream-to origin/master
          git remote -v
          echo "Checking out [$BRANCH_NAME]..."
          git checkout -b $BRANCH_NAME
          echo "Checking out [$BASE_BRANCH]..."
          git checkout $BASE_BRANCH
          git pull
          echo "Checking out [$BRANCH_NAME]..."
          git checkout $BRANCH_NAME
          git merge $BASE_BRANCH
          git status
          git status --ignored
          find . -type f | xargs ls -artl
          git add --all 
          git status
          git status --ignored
          echo "Commiting changes..."
          git rev-parse --show-toplevel
          git commit -a -m "Automatically generated by github-worflow[bot] for commit: $COMMIT_SHA"
          git status
          git status --ignored
          # https://stackoverflow.com/questions/64270867/auth-error-trying-to-copy-a-repo-with-github-actions
          git config -l | grep 'http\..*\.extraheader' | cut -d= -f1 | xargs -L1 git config --unset-all
          echo "Pushing [$BRANCH_NAME] to remote [$REMOTE]"
          git push -f $REMOTE $BRANCH_NAME
          echo "Submiting pull request..."
          gh pr create --title "Marketplace update from $BRANCH_NAME" --body "github-workflow" --base $BASE_BRANCH --head $BRANCH_NAME --repo $BASE_REPO/$REPO_PATH
